In [1]:
import numpy as np

# Array Creation

### Create a 1-dimensional array of integers from 1 to 10

In [2]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create a 2-dimensional array with random float values of shape (3,4)

In [3]:
b = np.random.rand(3,4)
b

array([[0.80727412, 0.56723298, 0.90484366, 0.78842132],
       [0.58033956, 0.5207747 , 0.88376987, 0.05523726],
       [0.14130226, 0.39434681, 0.47610848, 0.98808416]])

### Create a 3-dimensional array of zeros wiht shape (2,3,4)

In [4]:
c = np.zeros((2,3,4), dtype=int)
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

# Array Operations

### Given two 1- dimensional arrays, perform element-wise addition, subtraction, multiplication and division

In [5]:
a = np.arange(10,40,10)
b = np.arange(1,4)

In [6]:
add = a+b
add

array([11, 22, 33])

In [7]:
sub = a-b
sub

array([ 9, 18, 27])

In [8]:
mul = a*b
mul

array([10, 40, 90])

In [9]:
div = a/b
div

array([10., 10., 10.])

### Calculate mean, median, and standard deviation of given 1-dimensional array

In [10]:
c = np.random.rand(7)
c

array([0.40152212, 0.91938455, 0.45546883, 0.54853579, 0.81705485,
       0.87830194, 0.55762045])

In [11]:
mean = np.mean(c)
mean

0.6539840760711194

In [12]:
median = np.median(c)
median

0.5576204499453495

In [13]:
std = np.std(c)
std

0.19672265611546372

### Reshape a 1-dimensional array into a 2-dimensional array of shape(3,4)

In [14]:
d = np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
new_d = d.reshape(3,4)
new_d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Array Indexing and Slicing

### Extract fist row and last column of 2-dimensional array

In [16]:
a = np.linspace(1,99,10, dtype=int).reshape(2,5)
a

array([[ 1, 11, 22, 33, 44],
       [55, 66, 77, 88, 99]])

In [17]:
first_row = a[0,:]
first_row

array([ 1, 11, 22, 33, 44])

In [18]:
last_column = a[:,-1]
last_column

array([44, 99])

### Reverse the order of elements in a 1-dimensional array

In [19]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [20]:
rev_b = np.flip(b)
rev_b

array([4, 3, 2, 1, 0])

### Select elements from a 2- dimensional array that satisfy a specific condition(Values greater than a certain threshold)

In [21]:
c = np .linspace(1,100,20,dtype=int).reshape(2,-1)
c

array([[  1,   6,  11,  16,  21,  27,  32,  37,  42,  47],
       [ 53,  58,  63,  68,  73,  79,  84,  89,  94, 100]])

In [22]:
new_c = np.where(c%2==0,c,0)
new_c

array([[  0,   6,   0,  16,   0,   0,  32,   0,  42,   0],
       [  0,  58,   0,  68,   0,   0,  84,   0,  94, 100]])

# Array Broadcasting

### Add scalar value to each elements of 2-dimensional array

In [23]:
a = 100
b= np.linspace(1,99,20,dtype=int).reshape(2,-1)
b

array([[ 1,  6, 11, 16, 21, 26, 31, 37, 42, 47],
       [52, 57, 62, 68, 73, 78, 83, 88, 93, 99]])

In [24]:
c = a+b
c

array([[101, 106, 111, 116, 121, 126, 131, 137, 142, 147],
       [152, 157, 162, 168, 173, 178, 183, 188, 193, 199]])

### Multiply 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules

In [25]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [26]:
e = np.linspace(10,100,10,dtype=int).reshape(2,5)
e

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [27]:
f = d * e
f

array([[  0,  20,  60, 120, 200],
       [  0,  70, 160, 270, 400]])

# Linear Algebra

### Calculate the dot product of two 1-dimensioanal arrays

In [28]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [29]:
b = np.arange(10,50,10)
b

array([10, 20, 30, 40])

In [30]:
c=a.dot(b)
c

300

### Calculate the matrix multiplication of two 2-dimensional arrays

In [31]:
a = np.linspace(1,10,4,dtype=int).reshape(2,2)
a

array([[ 1,  4],
       [ 7, 10]])

In [32]:
b = np.linspace(11,20,4,dtype=int).reshape(2,2)
b

array([[11, 14],
       [17, 20]])

In [33]:
c=np.matmul(a,b)
c

array([[ 79,  94],
       [247, 298]])

### Find the inverse and determinant of a square matrix

In [34]:
mat = np.matrix('1,2;3,4')
mat

matrix([[1, 2],
        [3, 4]])

In [35]:
mat.getI()

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [36]:
np.linalg.det(mat)

-2.0000000000000004